### ISSUE TITLE
Clarification on Code Implementation of Query Radius (Rq) and Distance Measurement (Msq) in Figure 2

### ISSUE THREAD

**Issue by bruceleeEnglish** [Catoverflow/VBASE-artifacts#5]
Hello,

I have a question regarding the code implementation related to Figure 2 of the paper. Specifically, I am trying to understand where in the code the following two aspects are handled:

1. Determination of Radius (Rq):  
   In Figure 2, the radius \( Rq \) of the neighborhood around the query point \( q \) is defined as:  
   \[
   Rq = \max(\text{TopE}(\{\text{Distance}(q, v_j) \mid j \in [1, s - 1]\})),
   \]
   where \( \text{TopE} \) represents the set of the \( E \) nearest neighbors observed up to traversal step \( s \). During phase 1, this radius gradually decreases, and it stabilizes in phase 2. Could you point me to where in the code this radius \( Rq \) is calculated and updated during the index traversal?

2. Distance Measurement (Msq):  
   Additionally, the distance \( Msq \) is used to determine whether the query has moved beyond the neighborhood of \( q \) during the traversal. It is defined as the median of the distances between \( q \) and the vectors in the most recent traversal window (of size \( w \)):  
   \[
   Msq = \text{Median}(\{\text{Distance}(q, v_i) \mid i \in [s - w + 1, s]\}),
   \]
   where \( \text{Distance}(q, v_i) \) represents the distance between \( q \) and the traversed vector \( v_i \). Could you let me know where in the code this median-based distance \( Msq \) is computed to monitor the transition between phase 1 and phase 2?

Thank you in advance for your help!

**Comment by Catoverflow** [comment]
@bruceleeEnglish  Sorry for the late reply, I'm not actively monitoring this repo. It's more than one year ago and I may be wrong on code details.

For 1, it's `scanState->range`

For 2, it's https://github.com/Catoverflow/VBASE-artifacts/blob/92d6b31d613202a4ff4728b96badf19dd2d557d0/vectordb/src/index.cpp#L248-L266

Because to compare the median value of a queue (says with k elements) and the current distance value, you only need to remember the k/2 element's value using one variable. Here we set `threshold=5` so the length of queue is 10. That's not obvious though.

**Comment by Catoverflow** [comment]
I'm archiving this repo, if you have questions we can communicate over email as this repo is intended for artifacts only and have already complete it's job.
